### PR TITLE
Fix/in review status weird display

### LINKED ISSUE #9: "In Review" status not displaying and incrementing
### What Tales of Game are you working on?

Tales of Rebirth (PS2)

### Contact Details

Pegi

### What happened?

"In Review" status not incrementing and also not displaying

image

image

### PR DESCRIPTION
**Pull request by fortiersteven**

### CODE REVIEW

**Comment by fortiersteven** [comment]
@Fis-Ura You can review this one if the version I sent you works :)

File: TranslationApp/fMain.cs [hunk 1]
```diff
@@ -464,7 +464,28 @@ private void cbFileType_TextChanged(object sender, EventArgs e)
...
+                .Count();
+            }
+            else
+            {
+
+                //Count nb entries for the whole file
+                nbEntries = listEntries.SelectMany(x => x.Entries).Where(x => x.Status == status).Count();
+            }
+
+            return nbEntries.ToString();
```
Comment (Mc-muffin) [inline TranslationApp/fMain.cs:487]: We probably want to make this return the actual int value in the future

**Review by Mc-muffin — APPROVED** [review]
Looks fine, and it actually fixes #9
